# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20160226_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='description',
            field=models.CharField(default='Description', max_length=1500, verbose_name=b'newsletter description'),
        ),
    ]
