# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='description',
            field=models.CharField(default='Description of newsletter', max_length=1500, verbose_name=b'Description'),
        ),
    ]
